--- #---
version: '3'
volumes:
  db-data:
    external: false
  bundle-data:
    external: false
services:
  producer:
    build:
      context: '.'
      dockerfile: './docker/Dockerfile'
    entrypoint: './docker/entrypoint.sh'
    volumes:
      - '.:/var/www:cached'
      - './node_modules/:/var/www/node_modules'
    environment:
      AMQP_URL: amqp://guest:guest@rabbit:5672
      EXCHANGE: exchange
      MAXIMUM_ACTORS: 1500
      INTERVAL_TIME_IN_MS: 10
    hostname: producer

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
